import { useMemo, useRef, useState } from 'react';
import { Activity, CheckCircle2, CloudUpload, FileUp, LucideIcon, Moon, Play, RotateCcw, Sun, Trash2, UploadCloud, X, Zap } from 'lucide-react';
import { useUploadManager } from './hooks/useUploadManager'; import { UploadItem } from './types'; import { formatBytes, iconFor } from './utils'; import './index.css';
const statusLabel: Record<UploadItem['status'], string> = { pending: 'Pending', uploading: 'Uploading', completed: 'Completed', failed: 'Failed', cancelled: 'Cancelled' };
function App() { const manager = useUploadManager(); const input = useRef<HTMLInputElement>(null); const dragDepth = useRef(0); const [drag, setDrag] = useState(false); const [dark, setDark] = useState(() => localStorage.getItem('theme') === 'dark');
  const counts = useMemo(() => ({ total: manager.files.length, uploading: manager.files.filter(x => x.status === 'uploading').length, completed: manager.files.filter(x => x.status === 'completed').length, failed: manager.files.filter(x => x.status === 'failed').length }), [manager.files]);
  const add = (list: FileList | File[]) => manager.addFiles(Array.from(list)); const theme = () => { const d = !dark; setDark(d); localStorage.setItem('theme', d ? 'dark' : 'light'); };
  return <div className={dark ? 'app dark' : 'app'}><header><div className="brand"><div className="brand-mark"><CloudUpload size={22}/></div><div><h1>File Upload Manager</h1><p>Upload, track and manage your files</p></div></div><button className="icon-button" onClick={theme} aria-label="Toggle theme">{dark ? <Sun size={18}/> : <Moon size={18}/>}</button></header><main>
    <section className="hero"><div><span className="eyebrow"><Zap size={14}/> WORKSPACE</span><h2>Keep your files moving.</h2><p>Drop files into your workspace and watch every upload progress in real time.</p></div><div className="queue-chip"><Activity size={17}/><span><b>{counts.uploading} / {manager.maxConcurrency}</b> active uploads</span></div></section>
    <section className={`dropzone ${drag ? 'dragging' : ''}`} onDragEnter={e => { e.preventDefault(); dragDepth.current += 1; setDrag(true); }} onDragOver={e => e.preventDefault()} onDragLeave={e => { e.preventDefault(); dragDepth.current -= 1; if (dragDepth.current <= 0) { dragDepth.current = 0; setDrag(false); } }} onDrop={e => { e.preventDefault(); dragDepth.current = 0; setDrag(false); add(e.dataTransfer.files); }} onClick={() => input.current?.click()} role="button" tabIndex={0} aria-label="Upload files by browsing or dragging them here" onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); input.current?.click(); } }}><input ref={input} type="file" multiple hidden onChange={e => { if (e.target.files) add(e.target.files); e.currentTarget.value = ''; }}/><div className="upload-orb"><UploadCloud size={28}/></div><h3>{drag ? 'Drop files to upload' : 'Drag & drop files here'}</h3><p>or <span className="browse">Browse files</span></p><small>Multiple files supported · uploads are simulated locally</small></section>
    {manager.validationErrors.length > 0 && <div className="validation" role="alert"><span>{manager.validationErrors.join(' ')}</span><button onClick={manager.dismissValidation} aria-label="Dismiss validation message"><X size={15}/></button></div>}
    <section className="stats">{([['Total files', counts.total, FileUp, 'neutral'], ['Uploading', counts.uploading, Activity, 'blue'], ['Completed', counts.completed, CheckCircle2, 'green'], ['Failed', counts.failed, X, 'red']] as [string, number, LucideIcon, string][]).map(([label, value, Icon, tone]) => <div className="stat" key={label}><div className={`stat-icon ${tone}`}><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong></div></div>)}</section>
    <section className="files-section"><div className="section-head"><div><h2>Files</h2><p>{counts.total ? `${counts.total} file${counts.total === 1 ? '' : 's'} in your workspace` : 'Your uploads will appear here'}</p></div><div className="actions"><button className="secondary" onClick={manager.uploadAll} disabled={!manager.files.some(x => x.status === 'pending')}><Play size={15}/> Upload all</button><button className="secondary" onClick={manager.clearCompleted} disabled={!counts.completed}><Trash2 size={15}/> Clear completed</button></div></div>{manager.files.length === 0 ? <div className="empty"><div className="empty-icon"><FileUp size={27}/></div><h3>No files yet</h3><p>Upload your first file using drag & drop or the browse button above.</p></div> : <div className="file-list">{manager.files.map(item => <FileRow key={item.id} item={item} cancel={manager.cancel} retry={manager.retry} remove={manager.remove}/>)}</div>}</section>
    <p className="demo-note"><span>Tip</span> Rename a file to <b>fail-demo.pdf</b> to preview a recoverable upload failure and resume from its last completed chunk.</p>
  </main></div>;
}
function FileRow({ item, cancel, retry, remove }: { item: UploadItem; cancel: (id: string) => void; retry: (id: string) => void; remove: (id: string) => void }) { const Icon = iconFor(item.type, item.name); return <article className="file-row"><div className="file-main"><div className="file-icon"><Icon size={21}/></div><div className="file-name"><strong title={item.name}>{item.name}</strong><span>{formatBytes(item.size)} · {item.totalChunks} chunk{item.totalChunks === 1 ? '' : 's'}</span></div></div><div className="progress-area"><div className="progress-line"><span className={`status ${item.status}`} role="status"><i/> {statusLabel[item.status]}</span><b>{item.progress}%</b></div><div className={`bar ${item.status}`} role="progressbar" aria-label={`Upload progress for ${item.name}`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={item.progress}><span style={{ width: `${item.progress}%` }}/></div><small>{item.status === 'uploading' ? `Chunk ${Math.min(item.currentChunk, item.totalChunks)} of ${item.totalChunks}` : item.status === 'failed' ? item.error : item.status === 'pending' ? 'Waiting for an available upload slot' : item.status === 'cancelled' ? 'Upload stopped — ready to resume' : 'Upload complete'}</small></div><div className="row-actions">{item.status === 'uploading' && <button className="action cancel" onClick={() => cancel(item.id)} aria-label={`Cancel ${item.name}`}><X size={16}/> Cancel</button>}{(item.status === 'failed' || item.status === 'cancelled') && <button className="action retry" onClick={() => retry(item.id)} aria-label={`${item.status === 'failed' ? 'Resume' : 'Retry'} ${item.name}`}><RotateCcw size={16}/> {item.status === 'failed' && item.uploadedBytes ? 'Resume' : 'Retry'}</button>}{(item.status === 'completed' || item.status === 'failed' || item.status === 'cancelled') && <button className="remove" onClick={() => remove(item.id)} aria-label={`Remove ${item.name}`}><Trash2 size={16}/></button>}</div></article> }
export default App;
